<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<script>
     $(function() {
        var availableTitles = [
            <?php foreach ($search_array['titles'] as $albumTitle) :?>
            "<?php echo $albumTitle ?>",
            <?php endforeach;?>
        ];
        var availableArtists = [
            <?php foreach ($search_array['artists'] as $albumArtist) :?>
            "<?php echo $albumArtist ?>",
            <?php endforeach;?>
        ];
        var availableSeens = [
            <?php foreach ($search_array['seens'] as $albumSeens) :?>
            "<?php echo $albumSeens ?>",
            <?php endforeach;?>
        ];
        $("#title").autocomplete({
            source: availableTitles
        });
        $("#artist").autocomplete({
            source: availableArtists
        });
        $("#seen").autocomplete({
            source: availableSeens
        });
    });
</script>


<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'album', array(
            'action' => 'edit',
            'id' => $this->id,
                )
));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('title'));
//echo $this->formRow($form->get('artist'));
//echo $this->formSubmit($form->get('submit'));

echo $this->formCollection($form);

echo $this->form()->closeTag();
