<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<script>
$(document).ready(function() {
    $('#albumTable').dataTable( {
        "order": [[2, "asc"]],
        "processing": true,
        "serverSide": true,
        "ajax": "<?php echo $this->url('album', array('action' => 'indexAjax'));?>",
        "columnDefs": [
            {
                "visible": false,
                "targets": 0
            },
            {
                "render": function(data, type, row){
                    return "<a target=\"_blank\" href=\"".concat(data).concat("\"><img class=\"thumb\" src=\"").concat(data).concat("\" style=\"max-height:60px; width:auto;\"/></a>");
                },
                "searchable": false,
                "sortable": false,
                "targets": 1
            },
            {
                "searchable": true,
                "targets": 4
            },
            {
                "searchable": false,
                "targets": 5
            },
            {
                "searchable": false,
                "targets": 7
            },
            {
                "searchable": false,
                "targets": 8
            },
            {
                "render": function(data, type, row)
                    {
                        var anchor = "<a alt=\"<?php echo $this->translate('Edit');?>\" class=\"glyphicon glyphicon-pencil\" href=\"<?php echo $this->url('album', array('action' => 'edit'));?>/";
                        anchor = anchor.concat(row[0]);
                        anchor = anchor.concat("\"></a> ");
                        anchor = anchor.concat("<a alt=\"<?php echo $this->translate('Delete');?>\" class=\"glyphicon glyphicon-remove\" href=\"<?php echo $this->url('album', array('action' => 'delete'));?>/");
                        anchor = anchor.concat(row[0]);
                        anchor = anchor.concat("\"></a>");
                        return anchor;
                    },
                "sortable": false,
                "targets": 9
            },
        ],
    } );
});

function searchColumn(column, text){
    console.log("Serching " + text);
    $('#albumTable').dataTable().api().columns(column).search(text).draw();
}

</script>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <div class="btn-group" role="group">
        <a href="<?php echo $this->url('album', array('action' => 'add')); ?>"><button type="button" class="btn btn-default"><?php echo $this->translate('Add new album'); ?></button></a>
        <a href="<?php echo $this->url('album', array('action' => 'import')); ?>"><button type="button" class="btn btn-default"><?php echo $this->translate('Import a bunch of albums'); ?></button></a>
    </div>
</p>

<!-- Filtering options -->
<div class="btn-group btn-group-justified" role="group">
    <!-- Platform filter -->
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?php echo $this->translate('Select Platform'); ?><span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#" onclick="searchColumn(4, '')">All</a></li>
            <?php foreach ($this->platforms as $platform) { ?>
                <li><a href="#" onclick="searchColumn(4, '<?php echo $platform; ?>')"><?php echo $this->translate($platform); ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <!-- Watched filter -->
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?php echo $this->translate('Watched'); ?><span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#" onclick="searchColumn(6, '')">Any</a></li>
            <li><a href="#" onclick="searchColumn(6, 'none')">Non seen</a></li>
        </ul>
    </div>
</div>

<table id="albumTable" class="table">
    <thead>
        <tr>
            <th><?php echo $this->translate('Id'); ?></th>
            <th><?php echo $this->translate('Cover'); ?></th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Artist'); ?></th>
            <th><?php echo $this->translate('Platform'); ?></th>
            <th><?php echo $this->translate('Shelve'); ?></th>
            <th><?php echo $this->translate('Seen'); ?></th>
            <th><?php echo $this->translate('Register Date'); ?></th>
            <th><?php echo $this->translate('Edit Date'); ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><?php echo $this->translate('Id'); ?></th>
            <th><?php echo $this->translate('Cover'); ?></th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Artist'); ?></th>
            <th><?php echo $this->translate('Platform'); ?></th>
            <th><?php echo $this->translate('Shelve'); ?></th>
            <th><?php echo $this->translate('Seen'); ?></th>
            <th><?php echo $this->translate('Register Date'); ?></th>
            <th><?php echo $this->translate('Edit Date'); ?></th>
            <th>&nbsp;</th>
        </tr>
    </tfoot>
</table>