<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>"><?php echo $this->translate('Add new album'); ?></a>
</p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Artist'); ?></th>
        <th><?php echo $this->translate('Platform'); ?></th>
        <th><?php echo $this->translate('Shelve'); ?></th>
        <th><?php echo $this->translate('Cover'); ?></th>
        <th><?php echo $this->translate('Seen'); ?></th>
        <th><?php echo $this->translate('Register Date'); ?></th>
        <th><?php echo $this->translate('Edit Date'); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
            <td><?php echo $this->escapeHtml($album->platform); ?></td>
            <td><?php echo $this->escapeHtml($album->shelve); ?></td>
            <td><?php echo $this->escapeHtml($album->cover); ?></td>
            <td><?php echo $this->escapeHtml($album->seen); ?></td>
            <td><?php echo $this->escapeHtml($album->registerDate); ?></td>
            <td><?php echo $this->escapeHtml($album->editDate); ?></td>
            <td>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id));
    ?>">Edit</a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id));
    ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>