<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<script>
$(document).ready(function() {
    $('#albumTable').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "<?php echo $this->url('album', array('action' => 'indexAjax'));?>"
    } );
} );
</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>"><?php echo $this->translate('Add new album'); ?></a>
</p>
<table id="albumTable" class="table">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Artist'); ?></th>
            <th><?php echo $this->translate('Platform'); ?></th>
            <th><?php echo $this->translate('Shelve'); ?></th>
            <th><?php echo $this->translate('Cover'); ?></th>
            <th><?php echo $this->translate('Seen'); ?></th>
            <th><?php echo $this->translate('Register Date'); ?></th>
            <th><?php echo $this->translate('Edit Date'); ?></th>
            <!-- 
            <th>&nbsp;</th>
            -->
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Artist'); ?></th>
            <th><?php echo $this->translate('Platform'); ?></th>
            <th><?php echo $this->translate('Shelve'); ?></th>
            <th><?php echo $this->translate('Cover'); ?></th>
            <th><?php echo $this->translate('Seen'); ?></th>
            <th><?php echo $this->translate('Register Date'); ?></th>
            <th><?php echo $this->translate('Edit Date'); ?></th>
            <!-- 
            <th>&nbsp;</th>
            -->
        </tr>
    </tfoot>
</table>