<?php
// module/Album/view/album/user/edit.phtml:

$title = 'Edit user';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'user', array(
            'action' => 'edit',
            'id' => $this->id,
                )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();
